language: node_js
node_js:
- lts/*
- 6
sudo: required
services:
- docker
before_install:
- docker pull jubatus/jubatus
- docker run -d -p 9199:9199 -v $PWD:/opt/jubatus-tutorial-node jubatus/jubatus jubaclassifier
  -f /opt/jubatus-tutorial-node/config.json
- curl -SsO http://people.csail.mit.edu/jrennie/20Newsgroups/20news-bydate.tar.gz
- tar -xzf 20news-bydate.tar.gz
- sudo apt-get install jq
before_script:
- if [ $(echo "$(npm -v 2>&1 | cut -d. -f-2) < 4.2" | bc) -eq 1 ]; then npm run prepare; fi
script:
- node ./dist/tutorial.js -c ${CONCURRENCY:-100} > results.json
- cat results.json | jq '.[]|.valid' | sort | uniq -c |
  awk '{v[$2]=$1}END{exit!(v["true"]>v["false"])}'
notifications:
  slack:
    secure: bNrAoV7AseonBWYWTKSu5DZ6T5PWIiB6GJLIH0cZIOqxgI1BwYlNheoY0vZnbCyOVnRLnEFTcBY9nxjoLiBXpQJQV6/UvScUgkcdVLtq9gWLmMogCNlgL+4iUFrPh2xgtMqv4enhBNkBbp01qDxnZmvvBE5UMc2Pkyw8UqXw1oo=
