language: node_js
node_js:
- 6
sudo: required
services:
  - docker
before_install:
  - docker pull jubatus/jubatus
  - docker run -d -p 9199:9199 -v $PWD:/opt/jubatus-tutorial-node jubatus/jubatus jubaclassifier -f /opt/jubatus-tutorial-node/config.json
  - curl -SsO http://people.csail.mit.edu/jrennie/20Newsgroups/20news-bydate.tar.gz
  - tar -xzf 20news-bydate.tar.gz
  - sudo apt-get install jq
script:
  - env NODE_DEBUG= node tutorial.js